seed: 42

# Models
models:
  separate: True
  policy:  # Policy per fase grasp
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [256, 128, 64]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [256, 128, 64]
        activations: elu
    output: ONE

  # release_policy:  # <-- COMMENTATO per adesso, da aggiungere quando vorrai gestire il rilascio
  #   class: GaussianMixin
  #   clip_actions: False
  #   clip_log_std: True
  #   min_log_std: -20.0
  #   max_log_std: 2.0
  #   initial_log_std: 0.0
  #   network:
  #     - name: net
  #       input: STATES
  #       layers: [256, 128, 64]
  #       activations: elu
  #   output: ACTIONS
 # value:  # see deterministic_model parameters
   # class: DeterministicMixin
   # clip_actions: False
   # network:
  #    - name: net
  #      input: STATES
  #      layers: [256, 128, 64]
  #      activations: elu
 #   output: ONE

# Rollout memory
memory:
  class: RandomMemory
  memory_size: -1  # Automatico in base a agent:rollouts

# PPO agent configuration
agent:
  class: PPO  # <-- per ora è PPO normale (NON MultiAgentPPO)
  # agents: ["grasp_policy", "release_policy"]  <-- COMMENTATO, userai MultiAgentPPO quando aggiungi release
  rollouts: 96
  learning_epochs: 5
  mini_batches: 96
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 5.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: null
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.001
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1
  time_limit_bootstrap: False

  # logging and checkpoint
  experiment:
    directory: "hero_dragon_grasp"  # Solo grasping per ora
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto

# Trainer
trainer:
  class: SequentialTrainer
  timesteps: 38400  # 96 rollouts * 400 steps circa
  environment_info: log
  
  
  
# seed: 42

# models:
#   separate: True

#   arm:
#     class: GaussianMixin
#     clip_actions: False
#     clip_log_std: True
#     min_log_std: -20.0
#     max_log_std: 2.0
#     initial_log_std: 0.0
#     network:
#       - name: net
#         input: STATES
#         layers: [256, 128, 64]
#         activations: elu
#     output: ACTIONS

#   gripper2:
#     class: GaussianMixin
#     clip_actions: False
#     clip_log_std: True
#     min_log_std: -20.0
#     max_log_std: 2.0
#     initial_log_std: 0.0
#     network:
#       - name: net
#         input: STATES
#         layers: [128, 64]
#         activations: elu
#     output: ACTIONS

#   gripper1:
#     class: GaussianMixin
#     clip_actions: False
#     clip_log_std: True
#     min_log_std: -20.0
#     max_log_std: 2.0
#     initial_log_std: 0.0
#     network:
#       - name: net
#         input: STATES
#         layers: [64]
#         activations: elu
#     output: ACTIONS

# value:
#   separate: True

#   arm:
#     class: DeterministicMixin
#     clip_actions: False
#     network:
#       - name: net
#         input: STATES
#         layers: [256, 128]
#         activations: elu
#     output: ONE

#   gripper2:
#     class: DeterministicMixin
#     clip_actions: False
#     network:
#       - name: net
#         input: STATES
#         layers: [128]
#         activations: elu
#     output: ONE

#   gripper1:
#     class: DeterministicMixin
#     clip_actions: False
#     network:
#       - name: net
#         input: STATES
#         layers: [64]
#         activations: elu
#     output: ONE

# memory:
#   class: RandomMemory
#   memory_size: -1  # determined automatically by rollouts

# agent:
#   class: PPO
#   rollouts: 96
#   learning_epochs: 5
#   mini_batches: 96
#   discount_factor: 0.99
#   lambda: 0.95
#   learning_rate: 5.0e-04
#   learning_rate_scheduler: KLAdaptiveLR
#   learning_rate_scheduler_kwargs:
#     kl_threshold: 0.008
#   state_preprocessor: null
#   state_preprocessor_kwargs: null
#   value_preprocessor: null
#   value_preprocessor_kwargs: null
#   random_timesteps: 0
#   learning_starts: 0
#   grad_norm_clip: 1.0
#   ratio_clip: 0.2
#   value_clip: 0.2
#   clip_predicted_values: True
#   entropy_loss_scale: 0.001
#   value_loss_scale: 2.0
#   kl_threshold: 0.0
#   rewards_shaper_scale: 1
#   time_limit_bootstrap: False

#   experiment:
#     directory: "hero_dragon_madrl"
#     experiment_name: "grasping_coop_madrl"
#     write_interval: auto
#     checkpoint_interval: auto

# trainer:
#   class: SequentialTrainer
#   timesteps: 38400
#   environment_info: log

